//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IdCfgRom.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_IDCFGROM_DIALOG             102
#define IDD_PP_AMB                      107
#define IDR_MAINFRAME                   131
#define IDD_PP_ADMIF                    132
#define IDR_MAINFRAME1                  132
#define IDD_PP_ADM                      133
#define IDD_PP_DAC                      134
#define IDD_WRITE_READ_DIALOG           135
#define IDD_PP_FIFO                     136
#define IDD_PP_PLD                      137
#define IDD_PP_ADM2IF                   138
#define IDB_ARROW_DOWN                  138
#define IDB_ARROW_UP                    140
#define IDD_FILE_BASE_FILTER            141
#define IDC_READ                        1000
#define IDC_SAVE                        1001
#define IDC_FROMDEV                     1002
#define IDC_INTODEV                     1003
#define IDC_TABPAGE                     1004
#define IDC_ABOUT                       1005
#define IDC_HL_WWW                      1006
#define IDC_HL_Email                    1007
#define IDC_SAVEHEX                     1007
#define IDC_FIRMNAME                    1008
#define IDC_DEVICETYPE                  1009
#define IDC_COMMENT                     1009
#define IDC_SERIALNUM                   1010
#define IDC_NUMOFADMIF                  1011
#define IDC_SPINADMIF                   1012
#define IDC_BMTYPE                      1013
#define IDC_WRITE_SURNAME               1013
#define IDC_AMBEXT                      1014
#define IDC_BASE                        1014
#define IDC_AMBVERSION                  1015
#define IDC_SAVE_BASE                   1015
#define IDC_READ_BASE                   1016
#define IDC_WRITE_READ                  1017
#define IDC_SAVE_FILE_BIN               1017
#define IDC_READ_FILE                   1018
#define IDC_WRITE_NAME                  1019
#define IDC_CLEAR                       1019
#define IDC_ADMIFNUM                    1020
#define IDC_WRITE_DEVID                 1020
#define IDC_NUMOFADCFIFO                1021
#define IDC_WRITE_VER                   1021
#define IDC_NUMOFPLD                    1022
#define IDC_WRITE_ZAKAZ                 1022
#define IDC_NUMOFDACFIFO                1023
#define IDC_WRITE_PID                   1023
#define IDC_NUMOFDAC                    1024
#define IDC_DELETE_BASE                 1024
#define IDC_GEN1                        1025
#define IDC_WRITE_KEYWORD               1025
#define IDC_GEN2                        1026
#define IDC_WRITE_DATE                  1026
#define IDC_REFVOLTPVS                  1027
#define IDC_EDIT_BASE                   1027
#define IDC_STARTBE                     1028
#define IDC_WRITE_ZAKAZ2                1028
#define IDC_FILE_BASE_DIR               1028
#define IDC_PIOBE                       1029
#define IDC_SPINPLD                     1030
#define IDC_SPINDAC                     1031
#define IDC_PIOTYPE                     1032
#define IDC_SPINADMNUM                  1032
#define IDC_SPINADCFIFO                 1033
#define IDC_SPINDACNUM                  1034
#define IDC_ADMIFTYPE                   1034
#define IDC_SPINDACFIFO                 1035
#define IDC_SAVE_FILE_HEX               1035
#define IDC_SPINADMIFNUM                1036
#define IDC_FILTER                      1036
#define IDC_SPINPLDNUM                  1037
#define IDC_NAME                        1039
#define IDC_ADCFIFONUM                  1040
#define IDC_PID                         1040
#define IDC_ADCFIFOSIZE                 1041
#define IDC_SURNAME                     1041
#define IDC_ADCFIFOBITSWIDTH            1042
#define IDC_KEYWORD                     1042
#define IDC_SPINADCFIFONUM              1043
#define IDC_ZAKAZ                       1044
#define IDC_DACFIFONUM                  1045
#define IDC_VER                         1045
#define IDC_DACFIFOSIZE                 1046
#define IDC_DEVID                       1046
#define IDC_DACFIFOCYCLING              1047
#define IDC_DACFIFOBITSWIDTH            1048
#define IDC_DAY_START                   1048
#define IDC_SPINDACFIFONUM              1049
#define IDC_PLDNUM                      1050
#define IDC_YEAR_START                  1050
#define IDC_BASE_STATIC                 1050
#define IDC_PLDTYPE                     1051
#define IDC_MONTH_START                 1051
#define IDC_BASE_WORK_STATIC            1051
#define IDC_PLDVOLUME                   1052
#define IDC_PLDSIZE                     1052
#define IDC_DAY_END                     1052
#define IDC_NAME_STATIC                 1052
#define IDC_PLDPINS                     1053
#define IDC_YEAR_END                    1053
#define IDC_DEVID_STATIC                1053
#define IDC_PLDRATE                     1054
#define IDC_MONTH_END                   1054
#define IDC_VER_STATIC                  1054
#define IDC_PLDNAME                     1055
#define IDC_ZAKAZ_STATIC                1055
#define IDC_PID_STATIC                  1056
#define IDC_SURNAME_STATIC              1057
#define IDC_KEYWORD_STATIC              1058
#define IDC_DATE_STATIC                 1059
#define IDC_ADMCFG                      1060
#define IDC_HAND_WORK_STATIC            1060
#define IDC_ADMTYPE                     1061
#define IDC_ADMVERSION                  1062
#define IDC_ADMPID                      1063
#define IDC_WRITE_DEV                   1063
#define IDC_READ_WRITE_DEV              1063
#define IDC_ADMNUM                      1064
#define IDC_COMBO1                      1064
#define IDC_FILE_BASE_PATH              1068
#define IDC_STATIC_FILE_BASE_DIR        1069
#define IDC_DACNUM                      1070
#define IDC_DACBITS                     1071
#define IDC_DACENCODING                 1072
#define IDC_DACRATEMAX                  1073
#define IDC_DACRATEMIN                  1074
#define IDC_DACRANGEAF                  1075
#define IDC_DACRANGEPF                  1076
#define IDC_DACAFCOFF                   1077
#define IDC_DACLPFCOFF                  1078
#define IDC_DACHPFCOFF                  1079
#define IDC_DISDACLPFCOFF               1080
#define IDC_DISDACHPFCOFF               1081
#define IDC_AFSET                       1082
#define IDC_PFSET                       1083
#define IDC_DISDACRANGEAF               1084
#define IDC_DISDACAFCOFF                1085
#define IDC_DISDACRANGEPF               1087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
